# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffa1893a08c072cd4b832984d4235ca651b34544c4cb76c31e219db416a3b202664a83a441550e6a0610f6c42cb6cef9dcc51676c5a8c80d66a2347e23e2758

test:
  secret_key_base: b2448b0fb68b8d7d7572fd03d336fc9cded57d2f58192553c9b8b7d54a927ebc5ddfe24fedf53f9028809e1055c7ff5291e505650ee596d4dffaf9b341e854bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
